### ISSUE TITLE
JNISoundTouch的c代码有么

### ISSUE THREAD

**Issue by Igotyouinmysight** [dengzikun/WebRTC-APM-for-Android#4]
不大清楚在JNISoundTouch调用启动那4个方法的流程具体启动了些什么

**Comment by dengzikun** [comment]
soundtouch官网
https://www.surina.net/soundtouch/sourcecode.html

**Comment by Igotyouinmysight** [comment]
Thanks♪(･ω･)ﾉ


------------------ 原始邮件 ------------------
发件人: "dengzikun";<notifications@github.com>;
发送时间: 2017年9月1日(星期五) 上午10:05
收件人: "dengzikun/WebRTC-APM-for-Android"<WebRTC-APM-for-Android@noreply.github.com>; 
抄送: "彩虹的微笑"<296287129@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dengzikun/WebRTC-APM-for-Android] JNISoundTouch的c代码有么 (#4)




soundtouch官网
 https://www.surina.net/soundtouch/sourcecode.html
