### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION

### ISSUE THREAD

**Issue by ideastudios** [dengzikun/WebRTC-APM-for-Android#6]
下载后，通过ndk-build 生成so文件，并将其拷贝到libs目录下集成，参照demoActivity使用 会出现下面的错误  请问是什么问题，是不是哪里搞错了  包名与原文件一致

No implementation found for boolean com.android.webrtc.audio.MobileAEC.nativeCreateAecmInstance() (tried Java_com_android_webrtc_audio_MobileAEC_nativeCreateAecmInstance and Java_com_android_webrtc_audio_MobileAEC_nativeCreateAecmInstance__)

**Comment by dengzikun** [comment]
确认包名、类名是否一致。
