### ISSUE TITLE
Binaries compiled on MacOS missing symbols

### ISSUE THREAD

**Issue by AmolXio** [dengzikun/WebRTC-APM-for-Android#8]
Hi,

We tried to build libwebrtc_apms.so on MacOS using ndk-build, and although the build succeeds and generates the arm64-v8a/libwebrtc_apms.so and armeabi-v7a/libwebrtc_apms.so files as expected, those files don't appear to contain any symbols (as shown by either "dumpobj -t" or "nm").

Note that when I get the same pre-built binaries from WebRTC-APM-for-Android-Demo, those binaries seem to work.

Any suggestions on how to proceed?
Amol

**Comment by robmsmt** [comment]
I also had this problem. @dengzikun please suggest how to build in README from fresh project clone. Also x86_64 compilation is not possible therefore this will not work on the Emulator?

**Comment by dengzikun** [comment]
1. The libwebrtc_apms.so provides jni interface with JNINativeMethod instead of JEXPORT function.
    nm -D  libwebrtc_apms.so can display jni function arrays.

2. For no test environment, libwebrtc_apms.so  does not contain x86 code.You can add these X86 code files located in the webrtc directory.
